version: '3.9'

services:
  main_db:
    image: postgres:17.3-alpine
    restart: always
    volumes:
      - main_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=lozinka
      - POSTGRES_USER=postgres
      - POSTGRES_DB=main_db
  bank_db:
    image: postgres:17.3-alpine
    restart: always
    volumes:
      - bank_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=lozinka
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bank_db
  stock_db:
    image: postgres:17.3-alpine
    restart: always
    volumes:
      - stock_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=lozinka
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stock_db
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"  # RabbitMQ management console port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: user-service
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: user-service
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://main_db/main_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: lozinka
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_H2_CONSOLE_ENABLED: true
      SPRINGDOC_API_DOCS_PATH: /api-docs
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_BANK-SERVICE_URL: http://bank-service:8080
    depends_on:
      - main_db
      - rabbitmq
  email-service:
    build:
      context: .
      dockerfile: email-service/Dockerfile
    image: email-service
    ports:
      - "8081:8080"
    environment:
      SPRING_APPLICATION_NAME: email-service
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://main_db/main_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: lozinka
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_H2_CONSOLE_ENABLED: true
      SPRING_JPA_SHOW_SQL: true
      SPRINGDOC_API_DOCS_PATH: /api-docs
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: projekatsk2@gmail.com
      SPRING_MAIL_PASSWORD: ujcl wyrv fabj iuou
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: true
      SPRING_MAIL_PROPERTIES_MAIL_DEBUG: true
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - main_db
      - rabbitmq
  bank-service:
    build:
      context: .
      dockerfile: bank-service/Dockerfile
    image: bank-service
    ports:
      - "8082:8080"
    environment:
      SPRING_APPLICATION_NAME: bank-service
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://bank_db/bank_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: lozinka
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_H2_CONSOLE_ENABLED: true
      SPRING_JPA_SHOW_SQL: true
      SPRINGDOC_API_DOCS_PATH: /api-docs
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_USER-SERVICE_URL: http://user-service:8080
    depends_on:
      - bank_db
      - rabbitmq
  stock-service:
    build:
      context: .
      dockerfile: stock-service/Dockerfile
    image: stock-service
    ports:
      - "8083:8080"
    environment:
      SPRING_APPLICATION_NAME: stock-service
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://stock_db/stock_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: lozinka
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_H2_CONSOLE_ENABLED: true
      SPRING_JPA_SHOW_SQL: true
      SPRINGDOC_API_DOCS_PATH: /api-docs
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - stock_db
      - rabbitmq
volumes:
  main_db_data:
  bank_db_data:
  stock_db_data: